import { makeStyles, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
    // Hero
    hero: { backgroundColor: "var(--maq-off-white)", padding: "48px 32px" },
    heroGrid: {
        maxWidth: "1240px",
        margin: "0 auto",
        display: "grid",
        gridTemplateColumns: "1.3fr 1fr",
        gap: "48px",
        alignItems: "center",
        "@media (max-width: 960px)": { gridTemplateColumns: "1fr" },
    },
    eyebrow: {
        fontSize: "12px",
        fontWeight: 700,
        color: "var(--maq-red)",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        marginBottom: "12px",
        display: "block",
    },
    h1: {
        fontSize: "40px",
        lineHeight: 1.15,
        fontWeight: 700,
        color: "var(--maq-black)",
        letterSpacing: "-0.02em",
        margin: "0 0 16px",
    },
    heroSub: {
        fontSize: "15px",
        lineHeight: 1.6,
        color: "var(--maq-gray-600)",
        marginBottom: "24px",
        maxWidth: "640px",
    },
    btns: { display: "flex", gap: "12px", flexWrap: "wrap" },

    // Hero mosaic
    visual: {
        background: "var(--maq-surface-cream)",
        border: "1px solid var(--maq-red-pale)",
        borderRadius: "16px",
        padding: "20px",
        display: "grid",
        gap: "12px",
        boxShadow: "0 12px 32px rgba(15, 23, 42, 0.06)",
        color: "var(--maq-ink)",
    },
    tile: {
        background: "#fff",
        border: "1px solid var(--maq-border)",
        borderRadius: "10px",
        padding: "14px 16px",
    },
    tileTitle: {
        fontSize: "11px",
        textTransform: "uppercase",
        letterSpacing: "0.08em",
        color: "var(--maq-gray-500)",
        marginBottom: "8px",
        display: "flex",
        alignItems: "center",
        gap: "6px",
    },
    perfRow: { display: "flex", alignItems: "center", gap: "10px", marginTop: "6px" },
    perfLabel: { fontSize: "11px", width: "70px", color: "var(--maq-gray-500)" },
    perfTrack: { flex: 1, height: "6px", background: "var(--maq-gray-100)", borderRadius: "3px" },
    perfFill: { height: "100%", background: "var(--maq-red)", borderRadius: "3px" },
    pulseRow: { display: "flex", gap: "8px", alignItems: "center" },
    dot: { width: "10px", height: "10px", borderRadius: "50%", background: "var(--maq-red)" },
    pulseLabel: { fontSize: "12px", color: "var(--maq-gray-600)" },
    autoRow: {
        display: "flex",
        justifyContent: "space-between",
        fontSize: "12px",
        color: "var(--maq-ink)",
        marginTop: "4px",
    },
    heroImage: {
        width: "100%",
        aspectRatio: "16 / 10",
        display: "block",
        borderRadius: "10px",
        objectFit: "cover",
    },

    // Section commons
    section: { padding: "48px 32px", backgroundColor: "#fff" },
    sectionAlt: { padding: "48px 32px", backgroundColor: "var(--maq-off-white)" },
    inner: { maxWidth: "1240px", margin: "0 auto" },
    head: { textAlign: "center", marginBottom: "20px" },
    headCentered: { textAlign: "center", marginBottom: "28px" },
    secEyebrow: {
        fontSize: "12px",
        fontWeight: 700,
        color: "var(--maq-red)",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        display: "block",
        marginBottom: "6px",
    },
    title: {
        fontSize: "30px",
        fontWeight: 700,
        color: "var(--maq-black)",
        margin: "0 0 6px",
        letterSpacing: "-0.01em",
    },
    titleSm: {
        fontSize: "28px",
        fontWeight: 700,
        color: "var(--maq-black)",
        margin: "0 0 6px",
        letterSpacing: "-0.01em",
    },
    secSub: { fontSize: "14px", color: "var(--maq-gray-600)", margin: "0 auto", maxWidth: "780px", textAlign: "center" },

    // Capabilities — tabbed list + detail
    panel: {
        marginTop: "20px",
        background: "#fff",
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: "14px",
        padding: "28px",
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "40px",
        boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
        "@media (max-width: 960px)": { gridTemplateColumns: "1fr" },
    },
    iconBox: {
        width: "48px",
        height: "48px",
        borderRadius: "10px",
        background: "var(--maq-off-white)",
        color: "var(--maq-red)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: "18px",
    },
    detailName: {
        fontSize: "22px",
        fontWeight: 700,
        color: "var(--maq-black)",
        marginBottom: "10px",
    },
    detailDesc: {
        fontSize: "14px",
        color: "var(--maq-gray-600)",
        lineHeight: 1.65,
        marginBottom: "16px",
    },
    tagRow: { display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "20px" },
    tag: {
        fontSize: "11px",
        fontWeight: 600,
        color: "var(--maq-red)",
        background: "var(--maq-red-pale)",
        padding: "4px 8px",
        borderRadius: "4px",
        letterSpacing: "0.02em",
    },
    knowMore: {
        border: `1px solid var(--maq-red)`,
        color: "var(--maq-red)",
        background: "transparent",
        ":hover": { background: "var(--maq-red-pale)", color: "var(--maq-red)" },
    },
    rail: { display: "flex", flexDirection: "column", gap: "10px" },
    railBtn: {
        display: "flex",
        alignItems: "center",
        gap: "14px",
        width: "100%",
        padding: "14px 16px",
        background: "#fff",
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderLeftWidth: "1px",
        borderRadius: "8px",
        cursor: "pointer",
        textAlign: "left",
        transition: "all 0.15s",
        ":hover": { border: "1px solid var(--maq-card-hover-border)", boxShadow: "var(--maq-shadow-lift)", transform: "translateY(-2px)" },
    },
    railBtnActive: {
        border: "1px solid var(--maq-card-hover-border)",
        borderLeftWidth: "3px",
        boxShadow: "var(--maq-shadow-sm)",
    },
    railIcon: {
        width: "36px",
        height: "36px",
        borderRadius: "8px",
        background: "var(--maq-off-white)",
        color: "var(--maq-red)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    railText: { display: "flex", flexDirection: "column", gap: "2px" },
    railName: { fontSize: "14px", fontWeight: 700, color: "var(--maq-black)" },
    railTagline: { fontSize: "12px", color: "var(--maq-gray-600)" },
    footerLink: {
        marginTop: "20px",
        display: "inline-flex",
        alignItems: "center",
        gap: "6px",
        fontSize: "14px",
        fontWeight: 600,
        color: "var(--maq-red)",
        textDecoration: "none",
        ":hover": { textDecoration: "underline" },
    },
    buttonGroup: {
        marginTop: "20px",
        display: "flex",
        gap: "12px",
        flexWrap: "wrap",
        "@media (max-width: 640px)": { flexDirection: "column" },
    },

    // Outcomes
    outcomesGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "16px",
        "@media (max-width: 700px)": { gridTemplateColumns: "1fr" },
    },
    outcomeCard: {
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: "10px",
        padding: "24px",
        background: "#fff",
        transition: "all 0.2s",
        ":hover": {
            border: "1px solid var(--maq-card-hover-border)",
        },
    },
    outcomeIcon: {
        width: "44px",
        height: "44px",
        borderRadius: "10px",
        background: "var(--maq-red-pale)",
        color: "var(--maq-red)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: "14px",
    },
    outcomeName: {
        fontSize: "17px",
        fontWeight: 700,
        color: "var(--maq-black)",
        marginBottom: "8px",
    },
    outcomeDesc: { fontSize: "14px", color: "var(--maq-gray-600)", lineHeight: 1.55, margin: 0 },

    // Case studies
    caseGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 280px), 1fr))",
        gap: "16px",
    },
    caseCard: {
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: "12px",
        padding: "22px",
        background: "#fff",
        display: "flex",
        flexDirection: "column",
        gap: "10px",
        textDecoration: "none",
        color: "inherit",
        transition: "all 0.2s",
        ":hover": {
            border: "1px solid var(--maq-card-hover-border)",
            boxShadow: "var(--maq-shadow-lift)",
            transform: "translateY(-2px)",
        },
    },
    pill: {
        fontSize: "11px",
        fontWeight: 700,
        color: "var(--maq-red)",
        background: "var(--maq-red-pale)",
        padding: "3px 8px",
        borderRadius: "4px",
        letterSpacing: "0.06em",
        textTransform: "uppercase",
        alignSelf: "flex-start",
    },
    caseTitle: {
        fontSize: "17px",
        fontWeight: 700,
        color: "var(--maq-black)",
        lineHeight: 1.3,
        margin: 0,
    },
    caseTeaser: {
        fontSize: "14px",
        color: "var(--maq-gray-600)",
        lineHeight: 1.55,
        margin: 0,
        flex: 1,
    },
    caseRead: {
      display: "inline-block",
      fontSize: "13px",
      fontWeight: 700,
      lineHeight: 1.4,
      color: "var(--maq-red)",
      textDecoration: "none",
      },
    // Insights
    insGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "20px",
        "@media (max-width: 960px)": { gridTemplateColumns: "1fr" },
    },
    insCard: {
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: "12px",
        overflow: "hidden",
        background: "#fff",
        display: "flex",
        flexDirection: "column",
        textDecoration: "none",
        color: "inherit",
        transition: "all 0.2s",
        ":hover": {
            border: "1px solid var(--maq-card-hover-border)",
            boxShadow: "var(--maq-shadow-lift)",
            transform: "translateY(-2px)",
        },
    },
    insCover: {
        height: "100px",
        background:
            "linear-gradient(135deg, var(--maq-red-pale) 0%, var(--maq-off-white) 60%, var(--maq-surface-cream) 100%)",
        borderBottom: "1px solid var(--maq-border)",
    },
    insBody: { padding: "20px", display: "flex", flexDirection: "column", gap: "10px", flex: 1 },
    insTitle: {
        fontSize: "16px",
        fontWeight: 700,
        color: "var(--maq-black)",
        lineHeight: 1.35,
        margin: 0,
    },
    insTeaser: {
        fontSize: "13px",
        color: "var(--maq-gray-600)",
        lineHeight: 1.55,
        margin: 0,
        flex: 1,
    },
});
