import { makeStyles, tokens } from "@fluentui/react-components";

export const useProductFabricAdminAgentStyles = makeStyles({
    hero: { backgroundColor: "var(--maq-off-white)", padding: "48px 32px 56px" },
    heroGrid: {
        maxWidth: "1240px",
        margin: "0 auto",
        display: "grid",
        gridTemplateColumns: "1.3fr 1fr",
        gap: "48px",
        alignItems: "start",
        "@media (max-width: 960px)": { gridTemplateColumns: "1fr" },
    },
    eyebrow: {
        fontSize: "12px",
        fontWeight: 700,
        color: "var(--maq-red)",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        marginBottom: "12px",
        display: "block",
    },
    h1: {
        display: "block",
        fontSize: "40px",
        lineHeight: 1.15,
        fontWeight: 700,
        color: "var(--maq-black)",
        letterSpacing: "-0.02em",
        margin: "0 0 16px",
    },
    heroSub: {
        display: "block",
        fontSize: "15px",
        lineHeight: 1.6,
        color: "var(--maq-gray-600)",
        marginBottom: "24px",
        maxWidth: "640px",
    },
    btns: { display: "flex", gap: "12px", flexWrap: "wrap" },
    heroImageWrap: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "8px",
    },
    heroImage: {
        width: "100%",
        maxWidth: "520px",
        height: "auto",
        display: "block",
    },
    section: { padding: "48px 32px", backgroundColor: "#fff" },
    sectionAlt: { padding: "48px 32px", backgroundColor: "var(--maq-off-white)" },
    inner: { maxWidth: "1240px", margin: "0 auto" },
    head: { textAlign: "center", marginBottom: "28px" },
    headLeft: { marginBottom: "20px" },
    secEyebrow: {
        fontSize: "12px",
        fontWeight: 700,
        color: "var(--maq-red)",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        display: "block",
        marginBottom: "8px",
    },
    title: {
        display: "block",
        fontSize: "28px",
        fontWeight: 700,
        color: "var(--maq-black)",
        margin: "0 0 6px",
        letterSpacing: "-0.01em",
    },
    titleLg: {
        display: "block",
        fontSize: "30px",
        fontWeight: 700,
        color: "var(--maq-black)",
        margin: 0,
        letterSpacing: "-0.01em",
    },
    sub: { display: "block", fontSize: "14px", color: "var(--maq-gray-600)", margin: 0, maxWidth: "720px" },
    impactGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(4, 1fr)",
        gap: "16px",
        "@media (max-width: 960px)": { gridTemplateColumns: "repeat(2, 1fr)" },
    },
    impactCard: {
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: "10px",
        padding: "20px",
        background: "#fff",
        transition: "all 0.2s",
        ":hover": {
            border: `1px solid var(--maq-red)`,
            boxShadow: "0 6px 16px rgba(0,0,0,0.06)",
        },
    },
    impactMetric: {
        fontSize: "32px",
        fontWeight: 700,
        color: "var(--maq-red)",
        lineHeight: 1.1,
        marginBottom: "8px",
        letterSpacing: "-0.02em",
    },
    impactLabel: {
        fontSize: "14px",
        fontWeight: 600,
        color: "var(--maq-black)",
        lineHeight: 1.4,
        marginBottom: "8px",
    },
    impactSource: {
        fontSize: "11px",
        color: "var(--maq-gray-600)",
        textTransform: "uppercase",
        letterSpacing: "0.06em",
    },
    featGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(2, 1fr)",
        gap: "16px",
        "@media (max-width: 640px)": { gridTemplateColumns: "1fr" },
    },
    feat: {
        background: "#fff",
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: "12px",
        padding: "22px",
    },
    featHead: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        marginBottom: "8px",
    },
    featIconBox: {
        width: "36px",
        height: "36px",
        borderRadius: "8px",
        background: "var(--maq-red-pale)",
        color: "var(--maq-red)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    featTitle: { fontSize: "15px", fontWeight: 700, color: "var(--maq-black)" },
    featDesc: { fontSize: "13.5px", color: "var(--maq-gray-700)", lineHeight: 1.6, margin: 0 },
    caseGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "16px",
        "@media (max-width: 960px)": { gridTemplateColumns: "1fr" },
    },
    caseCard: {
        display: "flex",
        flexDirection: "column",
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: "12px",
        padding: "22px",
        background: "#fff",
        textDecoration: "none",
        color: "inherit",
        transition: "all 0.2s",
        ":hover": {
            border: `1px solid var(--maq-red)`,
            boxShadow: "0 6px 16px rgba(0,0,0,0.06)",
            transform: "translateY(-2px)",
        },
    },
    caseTag: { alignSelf: "flex-start", marginBottom: "12px" },
    caseTitle: {
        fontSize: "15px",
        fontWeight: 700,
        color: "var(--maq-black)",
        lineHeight: 1.4,
        marginBottom: "10px",
    },
    caseTeaser: {
        fontSize: "13px",
        color: "var(--maq-gray-600)",
        lineHeight: 1.55,
        flex: 1,
        marginBottom: "14px",
    },
    caseLink: {
        display: "inline-flex",
        alignItems: "center",
        gap: "4px",
        fontSize: "13px",
        fontWeight: 600,
        color: "var(--maq-red)",
    },
    seeAll: {
        marginTop: "20px",
        textAlign: "right",
        fontSize: "13px",
        fontWeight: 600,
    },
    seeAllLink: {
        color: "var(--maq-red)",
        textDecoration: "none",
        display: "inline-flex",
        alignItems: "center",
        gap: "4px",
    },
    quoteGrid: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "16px",
        "@media (max-width: 960px)": { gridTemplateColumns: "1fr" },
    },
    quote: {
        background: "#fff",
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: "12px",
        padding: "24px",
        position: "relative",
        margin: 0,
    },
    quoteMark: {
        position: "absolute",
        top: "4px",
        left: "16px",
        fontSize: "56px",
        color: "var(--maq-red)",
        opacity: 0.18,
        lineHeight: 1,
        fontFamily: "Georgia, serif",
    },
    quoteBody: {
        fontSize: "15px",
        color: "var(--maq-black)",
        lineHeight: 1.55,
        marginBottom: "14px",
        paddingTop: "16px",
    },
    quoteCite: {
        fontSize: "12px",
        color: "var(--maq-gray-600)",
        fontStyle: "normal",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: "0.05em",
    },
    mktGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "16px",
        "@media (max-width: 960px)": { gridTemplateColumns: "repeat(2, 1fr)" },
        "@media (max-width: 640px)": { gridTemplateColumns: "1fr" },
    },
    mktCard: {
        background: "#fff",
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: "10px",
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
        textDecoration: "none",
        color: "inherit",
        transition: "all 0.2s",
        ":hover": {
            border: `1px solid var(--maq-red)`,
            boxShadow: "0 6px 16px rgba(0,0,0,0.06)",
            transform: "translateY(-2px)",
        },
    },
    mktImg: {
        aspectRatio: "16 / 9",
        background:
            "linear-gradient(135deg, #ececec 0%, #f5f5f5 50%, #e6e6e6 100%)",
    },
    mktBody: { padding: "16px 18px 20px", display: "flex", flexDirection: "column", flex: 1 },
    mktPill: {
        alignSelf: "flex-start",
        fontSize: "10px",
        fontWeight: 700,
        color: "var(--maq-red)",
        background: "var(--maq-red-pale)",
        textTransform: "uppercase",
        letterSpacing: "0.06em",
        padding: "3px 8px",
        borderRadius: "4px",
        marginBottom: "10px",
    },
    mktTitleRow: {
        display: "flex",
        alignItems: "flex-start",
        gap: "8px",
        marginBottom: "8px",
    },
    mktTitle: {
        fontSize: "14px",
        fontWeight: 700,
        color: "var(--maq-black)",
        lineHeight: 1.4,
        flex: 1,
    },
    mktArrow: { color: "var(--maq-red)", flexShrink: 0, marginTop: "2px" },
    mktDesc: { fontSize: "12.5px", color: "var(--maq-gray-600)", lineHeight: 1.55, margin: 0 },
    banner: {
        display: "grid",
        gridTemplateColumns: "1fr auto",
        gap: "24px",
        alignItems: "center",
        background: "var(--maq-surface-cream)",
        border: "1px solid var(--maq-red-pale)",
        borderLeft: "4px solid var(--maq-red)",
        borderRadius: "12px",
        padding: "22px 24px",
        marginBottom: "20px",
        "@media (max-width: 720px)": { gridTemplateColumns: "1fr" },
    },
    bannerEyebrow: {
        display: "inline-block",
        fontSize: "10px",
        fontWeight: 700,
        color: "var(--maq-red)",
        background: "#fff",
        border: "1px solid var(--maq-red-pale)",
        textTransform: "uppercase",
        letterSpacing: "0.08em",
        padding: "3px 8px",
        borderRadius: "4px",
        marginBottom: "8px",
    },
    bannerTitle: {
        fontSize: "20px",
        fontWeight: 700,
        color: "var(--maq-black)",
        margin: "0 0 6px",
        letterSpacing: "-0.01em",
    },
    bannerDesc: {
        fontSize: "13.5px",
        color: "var(--maq-gray-700)",
        lineHeight: 1.55,
        margin: 0,
        maxWidth: "640px",
    },
    bannerBtns: { display: "flex", gap: "10px", flexWrap: "wrap" },
});
