import { makeStyles, tokens } from "@fluentui/react-components";

export const useProductPageStyles = makeStyles({
  hero: { backgroundColor: "var(--maq-off-white)", padding: "48px 32px 56px" },
  heroGrid: {
    maxWidth: "var(--maq-container-wide)",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "1.3fr 1fr",
    gap: "48px",
    alignItems: "center",
    "@media (max-width: 960px)": { gridTemplateColumns: "1fr" },
  },
  eyebrow: { fontSize: "12px", fontWeight: 700, color: "var(--maq-red)", letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: "12px", display: "block" },
  h1: { display: "block", fontSize: "40px", lineHeight: 1.15, fontWeight: 700, color: "var(--maq-black)", letterSpacing: "-0.02em", margin: "0 0 16px" },
  heroSub: { display: "block", fontSize: "15px", lineHeight: 1.6, color: "var(--maq-gray-600)", marginBottom: "24px", maxWidth: "640px" },
  btns: { display: "flex", gap: "12px", flexWrap: "wrap" },
  heroImageWrap: { display: "flex", alignItems: "center", justifyContent: "center", padding: "8px" },
  heroImage: { width: "100%", maxWidth: "520px", height: "auto", display: "block", borderRadius: "8px" },

  section: { padding: "48px 32px", backgroundColor: "#fff" },
  sectionAlt: { padding: "48px 32px", backgroundColor: "var(--maq-off-white)" },
  inner: { maxWidth: "var(--maq-container-wide)", margin: "0 auto" },
  head: { textAlign: "center", marginBottom: "28px" },
  headLeft: { marginBottom: "20px", textAlign: "center" },
  secEyebrow: { fontSize: "12px", fontWeight: 700, color: "var(--maq-red)", letterSpacing: "0.08em", textTransform: "uppercase", display: "block", marginBottom: "8px" },
  title: { display: "block", fontSize: "36px", lineHeight: 1.15, fontWeight: 700, color: "var(--maq-navy)", margin: "0 0 6px", letterSpacing: "-0.02em" },
  titleLg: { display: "block", fontSize: "36px", lineHeight: 1.15, fontWeight: 700, color: "var(--maq-navy)", margin: "0 0 10px", letterSpacing: "-0.02em" },
  sub: { display: "block", fontSize: "14px", color: "var(--maq-gray-600)", margin: "0 auto", maxWidth: "720px", textAlign: "center" },

  benGrid3: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "16px", "@media (max-width: 960px)": { gridTemplateColumns: "1fr" } },
  benGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "16px", "@media (max-width: 960px)": { gridTemplateColumns: "repeat(2, 1fr)" }, "@media (max-width: 640px)": { gridTemplateColumns: "1fr" } },
  benCard: {
    border: "0.5px solid var(--maq-border)",
    borderRadius: "12px",
    padding: "22px",
    background: "#fff",
    transition: "border-color 0.16s ease, box-shadow 0.16s ease",
    ":hover": { border: "1px solid var(--maq-card-hover-border)" },
  },
  benTitle: { fontSize: "16px", fontWeight: 700, color: "var(--maq-black)", marginBottom: "8px" },
  benDesc: { fontSize: "13.5px", color: "var(--maq-gray-700)", lineHeight: 1.6, margin: 0 },

  stepGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "20px", "@media (max-width: 960px)": { gridTemplateColumns: "1fr" } },
  stepGrid6: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "20px", "@media (max-width: 960px)": { gridTemplateColumns: "repeat(2, 1fr)" }, "@media (max-width: 640px)": { gridTemplateColumns: "1fr" } },
  stepCard: {
    background: "#fff",
    border: "0.5px solid var(--maq-border)",
    borderRadius: "12px",
    padding: "22px",
    position: "relative",
    transition: "border-color 0.16s ease, box-shadow 0.16s ease",
    ":hover": { border: "1px solid var(--maq-card-hover-border)" },
  },
  stepNum: { width: "32px", height: "32px", borderRadius: "50%", background: "var(--maq-red)", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, fontSize: "14px", marginBottom: "12px" },
  stepTitle: { fontSize: "15px", fontWeight: 700, color: "var(--maq-black)", marginBottom: "8px" },
  stepDesc: { fontSize: "13.5px", color: "var(--maq-gray-700)", lineHeight: 1.6, margin: 0 },

  featGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "16px", "@media (max-width: 640px)": { gridTemplateColumns: "1fr" } },
  feat: {
    background: "#fff",
    border: "0.5px solid var(--maq-border)",
    borderRadius: "12px",
    padding: "22px",
    transition: "border-color 0.16s ease, box-shadow 0.16s ease",
    ":hover": { border: "1px solid var(--maq-card-hover-border)" },
  },
  featHead: { display: "flex", alignItems: "center", gap: "10px", marginBottom: "8px" },
  featIconBox: { width: "36px", height: "36px", borderRadius: "8px", background: "var(--maq-red-pale)", color: "var(--maq-red)", display: "flex", alignItems: "center", justifyContent: "center" },
  featTitle: { fontSize: "15px", fontWeight: 700, color: "var(--maq-black)" },
  featDesc: { fontSize: "13.5px", color: "var(--maq-gray-700)", lineHeight: 1.6, margin: 0 },

  caseGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "16px", "@media (max-width: 960px)": { gridTemplateColumns: "1fr" } },
  caseCard: { display: "flex", flexDirection: "column", border: `1px solid ${tokens.colorNeutralStroke2}`, borderRadius: "12px", padding: "22px", background: "#fff", minHeight: "160px", transition: "all 0.2s", ":hover": { border: "1px solid var(--maq-card-hover-border)", boxShadow: "var(--maq-shadow-lift)", transform: "translateY(-2px)" } },
  caseTag: { alignSelf: "flex-start", marginBottom: "12px" },
  casePlaceholderTitle: { fontSize: "14px", fontWeight: 700, color: "var(--maq-gray-600)", marginBottom: "8px" },
  casePlaceholderText: { fontSize: "13px", color: "var(--maq-gray-600)", fontStyle: "italic" },

  quoteGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", "@media (max-width: 960px)": { gridTemplateColumns: "1fr" } },
  quote: { background: "#fff", border: `1px dashed ${tokens.colorNeutralStroke2}`, borderRadius: "12px", padding: "24px", minHeight: "140px" },
  quoteBody: { fontSize: "14px", color: "var(--maq-gray-600)", fontStyle: "italic", margin: 0 },

  priceGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "20px", "@media (max-width: 960px)": { gridTemplateColumns: "1fr" } },
  priceGrid2: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "20px", "@media (max-width: 720px)": { gridTemplateColumns: "1fr" } },
  priceCard: {
    background: "#fff",
    border: "0.5px solid var(--maq-border)",
    borderRadius: "12px",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    transition: "border-color 0.16s ease, box-shadow 0.16s ease, transform 0.16s ease",
    textDecoration: "none",
    color: "inherit",
    cursor: "pointer",
    ":hover": { border: "1px solid var(--maq-card-hover-border)", boxShadow: "var(--maq-shadow-lift)", transform: "translateY(-2px)" },
  },
  priceName: { fontSize: "14px", fontWeight: 700, color: "var(--maq-red)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: "10px" },
  priceAmount: { fontSize: "28px", fontWeight: 700, color: "var(--maq-black)", marginBottom: "2px" },
  priceTerm: { fontSize: "12px", color: "var(--maq-gray-600)", marginBottom: "16px" },
  priceList: { listStyle: "none", padding: 0, margin: "0 0 18px", display: "flex", flexDirection: "column", gap: "8px", flex: 1 },
  priceItem: { fontSize: "13px", color: "var(--maq-gray-700)", lineHeight: 1.5, paddingLeft: "16px", position: "relative", "::before": { content: '"✓"', position: "absolute", left: 0, color: "var(--maq-red)", fontWeight: 700 } },
  priceCta: { display: "inline-block", fontSize: "13px", fontWeight: 700, lineHeight: 1.4, color: "var(--maq-red)", textDecoration: "none", marginTop: "auto", paddingTop: "16px" },

  supportTable: { width: "100%", borderCollapse: "collapse", background: "#fff", border: `1px solid ${tokens.colorNeutralStroke2}`, borderRadius: "12px", overflow: "hidden" },
  supportTh: { background: "var(--maq-off-white)", padding: "14px 16px", textAlign: "left", fontSize: "13px", fontWeight: 700, color: "var(--maq-black)", borderBottom: `1px solid ${tokens.colorNeutralStroke2}` },
  supportTd: { padding: "12px 16px", fontSize: "13px", color: "var(--maq-gray-700)", borderBottom: `1px solid ${tokens.colorNeutralStroke2}` },

  mktGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "16px", "@media (max-width: 960px)": { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" }, "@media (max-width: 640px)": { gridTemplateColumns: "1fr" } },
  mktCard: { background: "#fff", border: `1px solid ${tokens.colorNeutralStroke2}`, borderRadius: "10px", overflow: "hidden", display: "flex", flexDirection: "column", textDecoration: "none", color: "inherit", transition: "all 0.2s", ":hover": { border: "1px solid var(--maq-card-hover-border)", boxShadow: "var(--maq-shadow-lift)", transform: "translateY(-2px)" } },
  mktImg: { height: "100px", background: "linear-gradient(135deg, var(--maq-red-pale) 0%, var(--maq-off-white) 60%, var(--maq-surface-cream) 100%)", borderBottom: "1px solid var(--maq-border)" },
  mktBody: { padding: "16px 18px 20px", display: "flex", flexDirection: "column", flex: 1, gap: "8px" },
  mktPill: { alignSelf: "flex-start", fontSize: "10px", fontWeight: 700, color: "var(--maq-red)", background: "var(--maq-red-pale)", textTransform: "uppercase", letterSpacing: "0.06em", padding: "3px 8px", borderRadius: "4px", marginBottom: "10px" },
  mktTitleRow: { display: "flex", alignItems: "flex-start", gap: "8px", marginBottom: "8px" },
  mktTitle: { fontSize: "14px", fontWeight: 700, color: "var(--maq-black)", lineHeight: 1.4, flex: 1 },
  mktArrow: { color: "var(--maq-red)", flexShrink: 0, marginTop: "2px" },
  mktDesc: { fontSize: "12.5px", color: "var(--maq-gray-600)", lineHeight: 1.55, margin: 0, flex: 1 },
  mktRead: {
    display: "inline-block",
    fontSize: "13px",
    fontWeight: 700,
    lineHeight: 1.4,
    color: "var(--maq-red)",
    textDecoration: "none",
    marginTop: "4px",
  },
});
